title: Jaehyeon Cho's Blog
description: "NLP(LLM, VLM), RAG, RLHF를 포함한 내용을 다룹니다."
description_en: "Exploring topics in NLP (LLM, VLM), RAG, and RLHF."
url: "https://bonin147.github.io" # GitHub Pages URL (예: https://username.github.io)
baseurl: "" # 레포지토리 이름 (username.github.io 사용 시 "" 로 변경)

# 빌드 설정
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 플러그인
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 작성자 정보
author:
  name: "JaeHyeon Cho"
  email: "jh.cho@lgcns.com"

# 소셜 링크
social:
  github: bonin147
  scholar: "https://scholar.google.com/citations?user=v4A8cuUAAAAJ&hl=ko"
  linkedin: "https://www.linkedin.com/in/jaehyeoncho0147/"
  instagram: bonin147

# Topics (네비게이션에 표시)
topics:
  - RLHF
  - NLP
  - RAG
  - Deep Learning
  - Preference Optimization

# 페이지네이션
paginate: 5

# 기본 Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "JaeHyeon Cho"
